# Generated by Django 5.1 on 2024-08-12 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blog', verbose_name='تصویر')),
                ('category_slug', models.CharField(max_length=255, verbose_name='اسلاگ')),
                ('author', models.CharField(max_length=255, verbose_name='نویسنده')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='BlogApp.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مطلب',
                'verbose_name_plural': 'وبلاگ',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Full',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introTitle', models.CharField(max_length=255, verbose_name='عنوان')),
                ('author', models.CharField(max_length=255, verbose_name='عنوان توضیحات')),
                ('content_desc', models.TextField(verbose_name='متن توضیحات')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.blog')),
            ],
            options={
                'verbose_name': 'توضیحات',
                'verbose_name_plural': 'توضیحات',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blog', verbose_name='تصویر')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='BlogApp.blog')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'گالری',
            },
        ),
    ]
