# Generated by Django 5.1 on 2024-08-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
