# Generated by Django 5.1 on 2024-08-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_blog_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='full',
            name='content_des2',
            field=models.TextField(default=' ', verbose_name='متن توضیحات'),
        ),
    ]
