# Generated by Django 5.1 on 2024-08-12 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Team', verbose_name='تصویر')),
                ('name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('role', models.CharField(max_length=255, verbose_name='موقعیت شغلی')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضای تیم',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, verbose_name='لینک')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Icon', verbose_name='آیکون')),
                ('title', models.CharField(max_length=255, verbose_name='نام شبکه اجتماعی')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='TeamApp.team')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
    ]
