# Generated by Django 5.1 on 2024-08-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('description', models.TextField(verbose_name='زیرنوشت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='تصویر')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': ' درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='زیرنوشت')),
            ],
            options={
                'verbose_name': 'هدر سایت',
                'verbose_name_plural': 'هدر سایت',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'همکار',
                'verbose_name_plural': 'همکاران',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255, verbose_name='عنوان')),
                ('title2', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('subtitle', models.TextField(verbose_name='زیرنوشت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'مطلب',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.TextField(verbose_name='زیرنوشت')),
            ],
            options={
                'verbose_name': 'مطلب',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('text', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceItems', to='HomeApp.service')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتمها',
            },
        ),
        migrations.CreateModel(
            name='TestItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('role', models.CharField(max_length=255, verbose_name='شغل')),
                ('text', models.TextField(verbose_name='زیرنوشت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='تصویر')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tetsItems', to='HomeApp.testimonial')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتمها',
            },
        ),
    ]
