# Generated by Django 5.1 on 2024-08-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'مشتریان', 'verbose_name_plural': 'مشتریان'},
        ),
    ]
