# Generated by Django 5.1 on 2024-08-12 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Project', verbose_name='تصویر')),
                ('short', models.CharField(max_length=255, verbose_name='توضیح کوتاه')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='لیبل')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='ServiceApp.service')),
            ],
        ),
        migrations.CreateModel(
            name='Full',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introTitle', models.CharField(max_length=255, verbose_name='عنوان')),
                ('title_desc', models.CharField(max_length=255, verbose_name='عنوان توضیحات')),
                ('content_desc', models.TextField(verbose_name='متن توضیحات')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ServiceApp.service')),
            ],
            options={
                'verbose_name': 'توضیحات',
                'verbose_name_plural': 'توضیحات',
            },
        ),
    ]
