# Generated by Django 5.1 on 2024-08-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='preview_title',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان پیش نمایش'),
            preserve_default=False,
        ),
    ]
