# Generated by Django 5.1 on 2024-08-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0002_remove_service_image_service_preview_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
    ]
