# Generated by Django 5.1 on 2024-08-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0003_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن توضیحات')),
                ('number', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'روند',
                'verbose_name_plural': 'روند ما',
            },
        ),
    ]
