# Generated by Django 5.1 on 2024-08-12 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Project', verbose_name='تصویر')),
                ('date', models.CharField(max_length=25, verbose_name='تاریخ پروژه')),
                ('category', models.ManyToManyField(related_name='project', to='ProjectApp.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Gallery2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Project', verbose_name='تصویر')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery2', to='ProjectApp.project')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'گالری دوم',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Project', verbose_name='تصویر')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='ProjectApp.project')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'گالری',
            },
        ),
        migrations.CreateModel(
            name='Full',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introTitle', models.CharField(max_length=255, verbose_name='عنوان')),
                ('fullImage', models.ImageField(blank=True, null=True, upload_to='Project', verbose_name='تصویر بزرگ')),
                ('title_desc', models.CharField(max_length=255, verbose_name='عنوان توضیحات')),
                ('content_desc', models.TextField(verbose_name='متن توضیحات')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProjectApp.project')),
            ],
            options={
                'verbose_name': 'توضیحات',
                'verbose_name_plural': 'توضیحات',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='لیبل')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Detail', to='ProjectApp.project')),
            ],
            options={
                'verbose_name': 'جزئیات',
                'verbose_name_plural': 'جزئیات',
            },
        ),
    ]
